
/**
 *
 * @author Nabeel Siddiqui
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        setDefaultCloseOperation(0);
    }

    public void displayProgressBar() {
        try {
            for(int intBarValue = 0; intBarValue <=100; intBarValue++) {
                Thread.sleep(200);
                lblPBValue.setText(Integer.toString(intBarValue)+"%");
                pbrSplashScreen.setValue(intBarValue);
            }
        }
        catch (Exception e) {
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblPBValue = new javax.swing.JLabel();
        pbrSplashScreen = new javax.swing.JProgressBar();
        lblHeader1 = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JLabel();
        lblBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employment Management System");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(300, 80));
        setMaximumSize(new java.awt.Dimension(750, 600));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblHeader.setBackground(new java.awt.Color(255, 255, 0));
        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 0, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setLabelFor(this);
        lblHeader.setText("Employment Management System");
        lblHeader.setToolTipText("");
        lblHeader.setOpaque(true);
        getContentPane().add(lblHeader);
        lblHeader.setBounds(70, 190, 617, 50);

        lblPBValue.setBackground(new java.awt.Color(0, 255, 255));
        lblPBValue.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblPBValue.setForeground(new java.awt.Color(0, 0, 255));
        lblPBValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPBValue.setLabelFor(this);
        lblPBValue.setText("%");
        lblPBValue.setToolTipText("");
        lblPBValue.setOpaque(true);
        getContentPane().add(lblPBValue);
        lblPBValue.setBounds(580, 270, 100, 40);

        pbrSplashScreen.setBackground(new java.awt.Color(255, 0, 255));
        pbrSplashScreen.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(pbrSplashScreen);
        pbrSplashScreen.setBounds(80, 320, 600, 30);

        lblHeader1.setBackground(new java.awt.Color(0, 0, 255));
        lblHeader1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(255, 0, 255));
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHeader1.setLabelFor(this);
        lblHeader1.setText("developed by");
        lblHeader1.setToolTipText("");
        lblHeader1.setName(""); // NOI18N
        lblHeader1.setOpaque(true);
        getContentPane().add(lblHeader1);
        lblHeader1.setBounds(80, 410, 250, 50);

        lblHeader2.setBackground(new java.awt.Color(0, 0, 255));
        lblHeader2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHeader2.setForeground(new java.awt.Color(0, 255, 255));
        lblHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader2.setLabelFor(this);
        lblHeader2.setText("developed by NABEEL SIDDIQUI");
        lblHeader2.setToolTipText("");
        lblHeader2.setName(""); // NOI18N
        lblHeader2.setOpaque(true);
        getContentPane().add(lblHeader2);
        lblHeader2.setBounds(80, 410, 589, 50);

        lblBackgroundImage.setBackground(new java.awt.Color(255, 255, 0));
        lblBackgroundImage.setForeground(new java.awt.Color(0, 0, 153));
        lblBackgroundImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EMSMain.png"))); // NOI18N
        lblBackgroundImage.setLabelFor(this);
        lblBackgroundImage.setToolTipText("");
        lblBackgroundImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBackgroundImage.setFocusable(false);
        lblBackgroundImage.setMaximumSize(new java.awt.Dimension(700, 869));
        lblBackgroundImage.setMinimumSize(new java.awt.Dimension(700, 869));
        lblBackgroundImage.setName(""); // NOI18N
        getContentPane().add(lblBackgroundImage);
        lblBackgroundImage.setBounds(0, 0, 750, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            //new SplashScreen().setVisible(true);
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackgroundImage;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeader2;
    public static javax.swing.JLabel lblPBValue;
    public static javax.swing.JProgressBar pbrSplashScreen;
    // End of variables declaration//GEN-END:variables
}
